DROP TABLE `user_roles`;
DROP TABLE `user_diagrams`;
DROP TABLE `users`;
CREATE TABLE `users` (
 USER_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 USERNAME varchar(40) NOT NULL,
 PASSWORD text NOT NULL,
 EMAIL text NOT NULL, 
 ENABLED tinyint(1) NOT NULL,
 PRIMARY KEY (USER_ID),
 UNIQUE KEY USERNAME (USERNAME)
);
CREATE TABLE `user_roles` (
 USER_ROLE_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 USER_ID int(10) unsigned NOT NULL,
 AUTHORITY varchar(40) NOT NULL,
 PRIMARY KEY (USER_ROLE_ID),
 FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
);
CREATE TABLE `user_diagrams` (
 USER_DIAGRAM_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
 USER_ID int(10) unsigned NOT NULL,
 DIAGRAM text NOT NULL,
 PRIMARY KEY (USER_DIAGRAM_ID),
 FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
);
INSERT INTO `users` (USERNAME, PASSWORD, EMAIL, ENABLED) VALUES
('ones', '7c4a8d09ca3762af61e59520943dc26494f8941b', 'ones@onesprice.com', 1);
INSERT INTO user_roles (USER_ID, AUTHORITY) VALUES
((SELECT USER_ID FROM `users` WHERE USERNAME = 'ones'), 'ROLE_USER');